### ISSUE TITLE
Cursor at the End of Control Blocks

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#10]
When clicking at the bottom of a control block, cursor ends up blinking in a different position.

![droplet-cursor](https://cloud.githubusercontent.com/assets/7230211/17931729/2dddf96e-6a0d-11e6-9a7b-675fbe9eee5c.png)

**Comment by dabbler0** [comment]
Will change. This is currently the intended behavior, though -- it's how Droplet works on Pencilcode and Code.org -- so if I don't push this change through in time note that launching with this behavior in is safe.

**Comment by kzidane** [comment]
Thanks for that, @dabbler0! Mind explaining why this was chosen deliberately? Really interested to know, maybe we should keep?

**Comment by dabbler0** [comment]
@kzidane At the time we figured we should just have the cursor go to the same place when you click on a block no matter where you clicked it, and decided that the top was better than the bottom. `droplet/cs50-unstable` now has functionality that tries to put the cursor nearby where you actually clicked the block, which will be merged into `droplet/cs50` as it gets tested.

**Comment by dabbler0** [comment]
Now also tested in `droplet/cs50-unstable`.

**Comment by dabbler0** [comment]
Merged!
