### ISSUE TITLE
Should We Allow Using All Blocks in .h Files?

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#11]
![droplet-header](https://cloud.githubusercontent.com/assets/7230211/17931861/a8a2fb36-6a0d-11e6-9548-302e6b0a7521.png)

@dmalan @dabbler0

**Comment by dmalan** [comment]
As opposed to what, @kzidane?

**Comment by kzidane** [comment]
@dmalan, the ones that are typically used. For example, the ones in the "Preprocessor" category like `#include` and `#define`? 

Do we want things from other categories (e.g., `for` loops, `main` functions, etc) to be available to use in a header file?

**Comment by dmalan** [comment]
Mind screenshotting the contents of the current categories?

>

**Comment by kzidane** [comment]
**Control:**
![control-0](https://cloud.githubusercontent.com/assets/7230211/17933587/efb6d748-6a14-11e6-9d06-7c0fa2bdda16.png)
![control-1](https://cloud.githubusercontent.com/assets/7230211/17933479/8f1669ee-6a14-11e6-8a0b-a2079675a3b2.png)
![control-2](https://cloud.githubusercontent.com/assets/7230211/17933480/8f1d4110-6a14-11e6-83e1-dd5e8f5d80ff.png)
![control-3](https://cloud.githubusercontent.com/assets/7230211/17933481/8f21b8ee-6a14-11e6-99e7-ab74dcdb811c.png)

**Data:**
![data-0](https://cloud.githubusercontent.com/assets/7230211/17933493/97a171ee-6a14-11e6-9eba-7274e5622259.png)
![data-1](https://cloud.githubusercontent.com/assets/7230211/17933494/97afffca-6a14-11e6-8744-3c0912d58872.png)

**Preprocessor:**
![preprocessor](https://cloud.githubusercontent.com/assets/7230211/17933526/aedd3b5e-6a14-11e6-91b0-0d6fa10d761d.png)

**Operations:**
![operations-0](https://cloud.githubusercontent.com/assets/7230211/17933553/c7aa3e84-6a14-11e6-8fe4-a439d54a4f88.png)
![operations-1](https://cloud.githubusercontent.com/assets/7230211/17933554/c7b568cc-6a14-11e6-81e6-bf18dee61b1a.png)

**Functions:**
![functions-0](https://cloud.githubusercontent.com/assets/7230211/17933508/a02cda2e-6a14-11e6-8bac-715a3e2bc21d.png)
![functions-1](https://cloud.githubusercontent.com/assets/7230211/17933509/a049b004-6a14-11e6-899f-0a5f64a3ae9c.png)
![functions-2](https://cloud.githubusercontent.com/assets/7230211/17933510/a068b9a4-6a14-11e6-92b6-650292bfcfc2.png)

**Comments:**
![comments](https://cloud.githubusercontent.com/assets/7230211/17933577/db062db2-6a14-11e6-8e70-59641ec479db.png)


Also, not sure if this is intended to be used the first couple of weeks or so? Do we need things like pointers, structs, malloc, etc? Just noticed some blocks are misplaced (e.g., should malloc go under Data)?

**Comment by kzidane** [comment]
P.S. I can share a workspace with you, if you'd like!

**Comment by dmalan** [comment]
Sure, please do!

**Comment by kzidane** [comment]
@dmalan wanna add input here?

**Comment by dmalan** [comment]
Hm, for now, I'm thinking we should keep things simple and not try to hide categories for `.h` files. But for a future version, we should consider.

But could we move `malloc` to the **Functions** category, alphabetically? I think we can remove `realloc`, since students can create that from the generic block.

And just so I'm sure, is this block the one students should use for declaring functions' prototypes? Or for calling some function?

![screen shot 2016-08-25 at 7 02 40 pm](https://cloud.githubusercontent.com/assets/788678/17988864/0f0bf7d0-6af7-11e6-9cee-bd2d7b09045b.png)

**Comment by kzidane** [comment]
@dmalan calling function.

**Comment by dmalan** [comment]
Which is the prototype block?

**Comment by kzidane** [comment]
I don't see any.

**Comment by kzidane** [comment]
`calloc` and `malloc` moved to **Functions** per f051bad78a5!
