### ISSUE TITLE
Should these console errors be constantly reported while typing?

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#15]
Screencast: [droplet-console-errors.zip](https://github.com/cs50/harvard.cs50.droplet/files/438342/droplet-console-errors.zip)

**Comment by dabbler0** [comment]
Yes -- or, at least, those are innocuous. Droplet uses ANTLR as its parser and is constantly checking to see if it can do a parse to blocks in the background while you're in text mode, for performance reasons. By default, ANTLR logs it to the console every time it encounters a parse error; I'm not sure how to suppress this.

**Comment by dabbler0** [comment]
Closing along with #22.

**Comment by dmalan** [comment]
@dabbler0 will this get rid of it? http://stackoverflow.com/a/35286575/5156190

**Comment by dabbler0** [comment]
@dmalan It did! I've switched over to this solution in `droplet/cs50-unstable`. Closing now.
