### ISSUE TITLE
disable ANTLR's console output

### ISSUE THREAD

**Issue by dmalan** [cs50/harvard.cs50.droplet#22]
Must be a way? Else really clutters console.

![screen shot 2016-08-26 at 7 54 01 am](https://cloud.githubusercontent.com/assets/788678/18004507/59419a42-6b62-11e6-8f9c-56e8795369cd.png)

**Comment by dabbler0** [comment]
I suppressed all logging from the worker thread that does the parsing (by reassigning `console.error` to a dud). Closing.
