### ISSUE TITLE
Text/Blocks option only appears when a .c file is opened, not when it's just been created and saved for the first time

### ISSUE THREAD

**Issue by dmalan** [cs50/harvard.cs50.droplet#23]
**when first created:**

![when first created](https://cloud.githubusercontent.com/assets/788678/18004545/93cf41be-6b62-11e6-8810-3a58bdd8457c.png)

**when re-opened:**

![when re-opened](https://cloud.githubusercontent.com/assets/788678/18004546/99f4ac00-6b62-11e6-842f-0c6640897f8a.png)

**Comment by dabbler0** [comment]
I can't actually reproduce this one on my offline instance -- what steps do you take to create the file? (it seems to be fine using +tab -> New file or File -> New file)

**Comment by dabbler0** [comment]
The issue was that the binding to mode changes for the initial session didn't update the button state. Current master should fix this.

**Comment by dmalan** [comment]
Oops, sorry, missed your earlier question!
