### ISSUE TITLE
when hovering over left/right arrows, shadow box doesn't have equal margins around arrows

### ISSUE THREAD

**Issue by dmalan** [cs50/harvard.cs50.droplet#25]
<img width="87" alt="screen shot 2016-08-26 at 8 01 40 am" src="https://cloud.githubusercontent.com/assets/788678/18004677/68124034-6b63-11e6-8d1f-ab889eba9755.png">

**Comment by dabbler0** [comment]
I believe this is fixed now:
![2017-06-29-151003_1366x768_scrot](https://user-images.githubusercontent.com/682790/27705864-5a4ea2a0-5cdd-11e7-9ccc-01e864bc3f5f.png)
