### ISSUE TITLE
error when failed to parse?

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#29]
Trying to toggle from Text to Blocks while there's syntax error, for example, shows spinner for a fraction of a second and then nothing happens. Should there be some sort of error reporting here?

**Comment by dabbler0** [comment]
This is easy to do, and I've put in an alert for when this happens:

![unnamed image 53](https://user-images.githubusercontent.com/682790/27215962-a5ae8400-5241-11e7-8961-9c62fc647188.png)

Not sure what kind of alert or what text is best; let me know and I will change.

**Comment by kzidane** [comment]
I think an alert might be a little annoying? A little [error dialog](https://cloud9-sdk.readme.io/docs/using-dialogs#dialog-error) might be better?

![dialog.error](https://files.readme.io/FB8MtsFrRM278jiJECQC_2015-02-13_2131.png)

As for wording, in case of error dialog, I think it should be something simple like:

> Error: couldn't switch to blocks due to syntax errors

@dmalan always has better wording though, so let's see what he thinks! :slightly_smiling_face:

**Comment by dmalan** [comment]
"Cannot convert to blocks! Does your code compile? Does it contain a syntax
error?"

**Comment by dabbler0** [comment]
![2017-06-21-001000_1366x768_scrot](https://user-images.githubusercontent.com/682790/27366783-4dae1e9a-5616-11e7-9dd7-e1c80514f403.png)

**Comment by dabbler0** [comment]
Closing.
