### ISSUE TITLE
Allow visual debugging

### ISSUE THREAD

**Issue by danallan** [cs50/harvard.cs50.droplet#3]
If we start the visual debugger, (see https://github.com/danallan/c9.ide.run.debug) while in block mode, the debugger pauses but the editor does not highlight the paused line.

In addition, breakpoints do not appear.

Compare, eg:
![screen shot 2016-08-04 at thu aug 4 17 08 50](https://cloud.githubusercontent.com/assets/877725/17418360/2d667e4a-5a66-11e6-843b-f19998f4f9c9.png)
![screen shot 2016-08-04 at thu aug 4 17 09 03](https://cloud.githubusercontent.com/assets/877725/17418377/46596d68-5a66-11e6-8783-dbfd33a22448.png)

**Comment by dabbler0** [comment]
@dmalan There's functionality in Droplet right now to highlight the block on a given line; we could have `debug50` check to see whether blocks mode is on and if so use the block highlight function instead?

**Comment by dmalan** [comment]
@dabbler0, https://github.com/cs50/harvard.cs50.debug/blob/master/bin/debug50

**Comment by dabbler0** [comment]
@dmalan Prototype of behavior: 
![screencast](https://cloud.githubusercontent.com/assets/682790/20022639/d35e76fc-a2b1-11e6-8c21-ae868126e7e5.gif)

This requires a pull to https://github.com/c9/c9.ide.run.debug, and right now the modification is Droplet-specific. I'll try to make it generally extensible and have the Droplet plugin hook into it.

**Comment by dabbler0** [comment]
@kzidane I was trying to prepare a pull request to `c9/core` for this, but it seems that in `c9/core` upstream, `c9.ide.run.debug` doesn't exist anymore. Do you have any pointers as to what I should modify instead for the latest version of c9?

**Comment by kzidane** [comment]
@dabbler0, it's at https://github.com/c9/c9.ide.run.debug!

**Comment by kzidane** [comment]
Curious whether this really requires modification to C9's debug plugin. If all we're doing is highlighting a block, and we can map lines to blocks, I suppose we could listen for [frameActivate](https://apidoc.c9.io/c9v3/#!/api/debugger-event-frameActivate), and process the active frame accordingly, no?

**Comment by dabbler0** [comment]
@kzidane You're right! `frameAc.tivate` works just fine. I'll move the Droplet plugin over to that instead

**Comment by dabbler0** [comment]
Committed to master now.
