### ISSUE TITLE
Deleting inner nested block deletes the outer one?

### ISSUE THREAD

**Issue by brianyu28** [cs50/harvard.cs50.droplet#35]
Seems like deleting nested blocks doesn’t always work as expected. If I have “int height = get_int();” where the “get_int()” block is nested inside of the larger “int height = ____;” block, and I then click on “get_int()” and then press delete, I would expect just the “get_int()” part to be deleted, but instead the entire “int height = get_int();” line is deleted.

**Comment by dabbler0** [comment]
There isn't currently a provision in the architecture for deleting nested blocks within the same line. Deletion is seen as a "cursor operation", where the cursor is the little black nub that sits between blocks, and that cursor can't know what nesting level it's at within the line.

If we changed this it would require a provision for a new kind of selection or cursor.

**Comment by dmalan** [comment]
@brianyu28 mind attaching a screenshot of this example?

**Comment by brianyu28** [comment]
Here's the screenshot: I can't delete `get_string()`, since clicking on the `get_string()` block and pressing delete triggers all of `string s = get_string()` to be deleted.

![nested_block](https://user-images.githubusercontent.com/16066224/27511455-a4629e30-58f2-11e7-9835-65e6d43e4e08.gif)

**Comment by dlloyd09** [comment]
Proposed solution: Eliminate delete key handler.

**Comment by dabbler0** [comment]
Delete key disabled as of e63911131b5cb731489527ac098a6232edfb59ae
