### ISSUE TITLE
Is it possible to declare a function that returns a pointer?

### ISSUE THREAD

**Issue by brianyu28** [cs50/harvard.cs50.droplet#36]
Doesn’t seem to give me that option in the dropdown.

**Comment by dabbler0** [comment]
It's not in the dropdown, but you can type `int*` for instance if you want one. Note that the real C parse for this is kind of weird, and the Droplet blockification will reflect that:

```
int* myFun()
```

Actually parses like:
```
[[[int[* myFun]]()]
```

Where `*` is closer associated with `myFun` than with `int`. If we wanted to put something like this in the palette, it would probably not be in the return type dropdown, but instead by a block `*myFun` that you could drag out into the slot for your function name.

**Comment by dabbler0** [comment]
Like so:
![unnamed image 50](https://cloud.githubusercontent.com/assets/682790/26662267/aed5164a-4650-11e7-8987-434f4e2a7fad.png)

**Comment by dmalan** [comment]
Can a user type `*main` for a function name in order for it to parse like a function pointer? If so, that feels reasonable, no need for custom block.

**Comment by dabbler0** [comment]
Yep, they can.

**Comment by dmalan** [comment]
So long as the * can be typed either after a var name or before a function name, that feels fine, since folks are unlikely to use GUI mode once at pointers!
