### ISSUE TITLE
since we have a struct_name.member_name block, we also have a struct_ptr->member_name block

### ISSUE THREAD

**Issue by brianyu28** [cs50/harvard.cs50.droplet#37]

**Comment by dabbler0** [comment]
@dmalan Easy to add this if we decide we want it.

**Comment by dmalan** [comment]
Indeed, let's add this one.

**Comment by dabbler0** [comment]
Added it here:

![2017-06-21-001550_1366x768_scrot](https://user-images.githubusercontent.com/682790/27366861-e21a2ede-5616-11e7-8186-8da38fe35dd4.png)

Let me know if you want any text changes or if it should go in a different position.

**Comment by dabbler0** [comment]
Closing this due to lack of objections.
