### ISSUE TITLE
"Tab" key triggers unsaved warning

### ISSUE THREAD

**Issue by brianyu28** [cs50/harvard.cs50.droplet#38]
I can cycle through the three parts of a “for” loop by pressing the tab key, but when I do, CS50 IDE seems to think I’m exiting the file, because I immediately get the warning “You haven’t saved your changes to foo.c yet” appearing.

@kzidane, maybe you have insight into why this could be?

**Comment by kzidane** [comment]
Yeah, it seems Tab not only cycles through the three parts, but also focuses terminal in the console pane (if open), so it's expected to see unsaved warning. We should probably look into why it focuses the terminal at the same time, and prevent that.

**Comment by dmalan** [comment]
Do the blocks have `tabindex` attributes?

**Comment by dabbler0** [comment]
The blocks do not, but the editor itself does.

**Comment by dmalan** [comment]
Can we avoid the terminal window getting focus, for accessibility's sake?

**Comment by dabbler0** [comment]
Fixed this by calling `event.stopPropagation()` on the tab key press event.

**Comment by kzidane** [comment]
Still there it seems, I'm afraid! :slightly_frowning_face: 

![tab-unsaved](https://user-images.githubusercontent.com/7230211/28798282-02f168aa-7612-11e7-9993-cd52e8a8d44b.gif)

**Comment by dabbler0** [comment]
Weird. The fix that I had made for this at the time was somehow gone in master -- I think it might have been destroyed in some bad merge. I've put it back now and this should be fixed.
