### ISSUE TITLE
should be able to select category while text is in search bar?

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#42]
Right now, if there's text in the search bar, the categories are disabled, and I can't select any of them until I click inside the search bar to clear (which I'm not sure should be the case?) or manually clear the text. Should that indeed be the case?

![search](https://cloud.githubusercontent.com/assets/7230211/26658927/7b721556-466d-11e7-8724-4337de03dbfc.png)

**Comment by dabbler0** [comment]
The categories are filtered so that you can only select the ones that contain a block that matches your text. This was chosen intentionally so that if you're looking for a block that's actually in a different section, it would light up so you would know.

**Comment by kzidane** [comment]
Ah, makes sense! Wondering if it'd be better if clicking disabled category, while searching, simply clears the search and selects that category instead of having to manually clear the search then selecting?

**Comment by dmalan** [comment]
Agreed, that sounds wise!

**Comment by dabbler0** [comment]
Now implemented.
