### ISSUE TITLE
call main's first argument argc?

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#44]
Since `argc` is more conventional, and for consistency?

![main](https://user-images.githubusercontent.com/7230211/27971649-7c5b3f94-6321-11e7-9fc3-7d75c0747261.png)

**Comment by dabbler0** [comment]
Done

**Comment by kzidane** [comment]
Still called `n` it seems?

![argc](https://user-images.githubusercontent.com/7230211/29630768-447014a6-880b-11e7-8773-5ff2bb812cce.png)
