### ISSUE TITLE
fails to parse one-line functions

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#45]
probably not common, but technically not a syntax error

![function](https://user-images.githubusercontent.com/7230211/27971888-5912b188-6322-11e7-8bd8-1331d88f76cb.png)

**Comment by dabbler0** [comment]
This is now fixed.

Sometimes it will look ugly if you do something like this:

```
int main() { printf("hi"); }
```

It doesn't know what to do with the whitespace around "printf" so it inserts it as some extra blocks. It will still parse, though, and you can remove the extra blocks. Presumably we don't encourage this style.
