### ISSUE TITLE
can't edit empty multiline comments in blocks

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#46]
![multiline-comment](https://user-images.githubusercontent.com/7230211/27972154-4cae815a-6323-11e7-9c55-9aae5260219e.png)
![multiline-comment-blocks](https://user-images.githubusercontent.com/7230211/27972155-4cb1fc54-6323-11e7-829a-0a4be0d06253.png)

**Comment by dabbler0** [comment]
You actually can't edit any multiline comments in Droplet. We had a draft of a UI for editing multiline comments but it broke everything else and so we decided to cut it. I'm not sure I'll have time to implement this this week.

**Comment by dabbler0** [comment]
@dmalan What is the goal for this issue for Aug 11?

**Comment by dmalan** [comment]
We can leave these uneditable.
