### ISSUE TITLE
context menu items don't work in blocks

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#47]
![context-menu](https://user-images.githubusercontent.com/7230211/27973041-846255d8-6326-11e7-8702-1058e912f5c2.gif)

**Comment by dabbler0** [comment]
Cut, Copy, and Paste from the context menu should now work in blocks. Working on Select All.

Caveat: Droplet's cut/copy/paste mechanism has always been a weird UI. To "select" a block you have to use the lasso select by clicking out in space and dragging. Not many users figure this UI out without being told. This should probably change in the future but requires more discussion on what the proper UI would be and then some infrastructure changes to implement it.

**Comment by dmalan** [comment]
@dabbler0 what would be involved in allowing user to right-click right on block, as @kzidane's mockup does? For now, could we disable the context menu altogether for blocks?

**Comment by dlloyd09** [comment]
Adhere to Scratch's paradigm here for inspiration of how to approach. @kzidane mind adding a short video of what Scratch does for illustration?

**Comment by kzidane** [comment]
Fyi, this seems to be breaking the paste functionality in ace:

![paste](https://user-images.githubusercontent.com/7230211/28799721-be4ec322-7617-11e7-803e-3fd5c963ce54.gif)

Scratch's context menu doesn't have copy/paste it seems:

![scratch](https://user-images.githubusercontent.com/7230211/28799763-db59b526-7617-11e7-9266-624a99fa3ab3.png)

**Comment by dabbler0** [comment]
f8326c5 Disabled those menu options for now; definitely possible to do Scratch-like behavior but I think more time than it is worth. The commit should also fix the bug pointed out above.
