### ISSUE TITLE
#define sometimes shows one field, sometimes two

### ISSUE THREAD

**Issue by brianyu28** [cs50/harvard.cs50.droplet#51]
When I have the line:

```c
#define MAX(a, b) (a > b ? a : b)
```

the block shows up with two input fields. When I get rid of the space in `(a, b)` as per:

```c
#define MAX(a,b) (a > b ? a : b)
```

then the block only has one input field. Example:

![gwjgg9qpfx](https://user-images.githubusercontent.com/16066224/27981837-c5e86e0e-6360-11e7-977f-8ba665760270.gif)

**Comment by dabbler0** [comment]
This should now be fixed.
