### ISSUE TITLE
blocks toggle available for non .c files

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#54]
![blocks-toggle](https://user-images.githubusercontent.com/7230211/28239663-ac7ca540-693f-11e7-874a-4baac648fb95.png)

**Comment by kzidane** [comment]
If `@useBlocksByDefault` is `true`, creating new file puts it in Blocks mode:

![blocks-by-default](https://user-images.githubusercontent.com/7230211/28239767-4ea3ed28-6941-11e7-8e44-8d06aa69a40f.png)

fyi, @dabbler0, this is in production now!

**Comment by dlloyd09** [comment]
Let's test in production and if it works, close this issue.
CC @kzidane
