### ISSUE TITLE
create visual text/blocks ("puzzle piece") icon in menu bar at bottom right

### ISSUE THREAD

**Issue by dlloyd09** [cs50/harvard.cs50.droplet#59]

**Comment by kzidane** [comment]
Fyi, current Blocks menu item doesn't always show up:

![blocks-menu-item](https://user-images.githubusercontent.com/7230211/28725889-f08c4cd4-738c-11e7-9e4a-81915802bdc5.png)

**Comment by dabbler0** [comment]
The button is now in the correct place, but just says "Blocks" or "Text". Could you send me images for glyphs to use? Then I can drop those in and close this.

**Comment by dabbler0** [comment]
@dmalan @kzidane

**Comment by dlloyd09** [comment]
@dabbler0 can we try the puzzle piece icon called "Extensions" here from material.io? 
https://material.io/icons/
https://google.github.io/material-design-icons/#icon-images-for-the-web

**Comment by dabbler0** [comment]
Done.
