### ISSUE TITLE
Disable for non-c files?

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#6]
The "Blocks" button appears on the bottom-right corner of ace, even though the file is not .c file. I don't think this should be the case? Clicking the button results in the error per the screenshots.

![droplet-js](https://cloud.githubusercontent.com/assets/7230211/17871753/34c0b056-68bd-11e6-9537-b6ac0ffb06fc.png)
![droplet-text](https://cloud.githubusercontent.com/assets/7230211/17871754/34eee4f8-68bd-11e6-9d37-f31b2e052412.png)

**Comment by dmalan** [comment]
Able to ascertain how to fix?

**Comment by kzidane** [comment]
Will try!

**Comment by dabbler0** [comment]
I have fixed this issue and pushed to master in commit d577c197efbcf30ffa8cdedc0a0062b8312ae19c.
