### ISSUE TITLE
Text/Blocks toggle disappears when moving tab between panes

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#63]
Seems it disappears if I move the tab to a different pane, and back per the GIF below:

![tab-moving](https://user-images.githubusercontent.com/7230211/28795620-8a844224-7608-11e7-90fa-bbd9dfcc4576.gif)

**Comment by dabbler0** [comment]
Is this still happening on current master? I'm unable to reproduce.

**Comment by kzidane** [comment]
Unable to reproduce either. Closing for now.
