### ISSUE TITLE
uses 2 spaces for indentation

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#64]
Pardon the colors. Recorder issue.

![indentation](https://user-images.githubusercontent.com/7230211/28796307-0ad127ec-760b-11e7-8446-b7091a2c9e4f.gif)

**Comment by dabbler0** [comment]
We want to change this to four spaces?

**Comment by kzidane** [comment]
@dabbler0 ideally yes per https://manual.cs50.net/style!

**Comment by kzidane** [comment]
Or actually should it be the number of spaces currently set per `ace` which is 4 by default @dmalan?

**Comment by dabbler0** [comment]
Just using 4 spaces for now as I can't figure out how to bind to `ace` preference changes. This is in effect now in master.

**Comment by kzidane** [comment]
Is it `project/ace/@tabSize` per chance https://github.com/c9/core/blob/master/plugins/c9.ide.ace/ace.js#L770?

**Comment by dmalan** [comment]
@dabbler0, did @kzidane's proposal help?

**Comment by dabbler0** [comment]
The tab size now reflects `/project/ace/@tabSize`, which is set from preferences. I've noticed that this can be different from the tab size shown in the status bar, so I'm not sure what the tab size in the status bar is.

**Comment by kzidane** [comment]
Seems to indent correctly if I drag and drop the puzzle pieces, but not when I write part of the code:

![indent](https://user-images.githubusercontent.com/7230211/29996037-0bfae1e8-8fc5-11e7-9393-f02d847c1f3e.gif)

**Comment by crossroads1112** [comment]
Relevant excerpt:
https://github.com/cs50/harvard.cs50.droplet/blob/a44a7b8fa78a6df4253a62e1273f396db1d41c14/droplet.js#L392-L414
