### ISSUE TITLE
a == b as a placeholder as opposed to 'condition'?

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#66]
Should that indeed be the case?

![aequalsb](https://user-images.githubusercontent.com/7230211/28797986-23169aa2-7611-11e7-88a9-a788b02c426f.gif)

**Comment by dabbler0** [comment]
This is the case right now. @dmalan if we want to change this it is not difficult, let me know if we should.

**Comment by dmalan** [comment]
Let's just change to "condition" too?

**Comment by dabbler0** [comment]
Fixed now.
