### ISSUE TITLE
Update v103 leaves metadata files behind

### ISSUE THREAD

**Issue by MadDogDean** [cs50/harvard.cs50.droplet#68]
Updating IDE from v102 to v103 leaves current and historical metadata behind.

Some of the metadata is from files created and subsequently deleted.

![cs50 v103](https://user-images.githubusercontent.com/23712335/28807889-b96cde82-76aa-11e7-83c3-e9d055fcb40c.jpg)

**Comment by kzidane** [comment]
Hi @MadDogDean, this doesn't really look like an issue to me. The `~/workspace/.c9/` directory is expected to contain some file revision history and metadata. You may hide this folder by following the instructions per https://manual.cs50.net/ide/faqs#i-see-a-c9-folder-appearing-right-under-my-workspace-folder-that-i-havent-created-is-this-normal. 

Any chance this might have broken anything for you?

**Comment by MadDogDean** [comment]
Hey @kzidane, the issue doesn't seem to cause anything to break, I never had these files come up before, but with the quick release of so many updates since v99, I just wanted to ensure nothing got tripped up.

Cheers

**Comment by kzidane** [comment]
No worries, @MadDogDean. We're more than happy to help if something ever comes up, so please feel free to reach out if you need assistance with anything course-related! Closing this. Thank you!
