### ISSUE TITLE
literally shows "extension" and "subject" for the toggles

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#69]
That's Chrome 60.0.3112.78 on Ubuntu 16.04.2.

![extension](https://user-images.githubusercontent.com/7230211/29627407-fc84a22a-87ff-11e7-9cb3-00f265c075e4.png)

![subject](https://user-images.githubusercontent.com/7230211/29627412-00bb25e4-8800-11e7-9261-830cc93b5e97.png)

**Comment by dabbler0** [comment]
I can't reproduce this with Chrome 60.0.3312.101 on Windows, nor on Chrome 59.0.3071.115 on Linux.

This does happen for a short loading time before the font loads for me; I'll see if I can make some kind of graceful loading so that it's a single letter or something until the font loads.

**Comment by dabbler0** [comment]
Ah! I figured it out. Whether this bug occurs depends on whether the Droplet stylesheet is loaded before or after the core stylesheet. I fixed this by making the material icons font a property on the element rather than a class property.
