### ISSUE TITLE
Opening non-C files

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#7]
When opening non-C file (e.g., one without extension), there's an error in the console

> Uncaught TypeError: aceEditor.updateNewSession is not a function

caused by line https://github.com/cs50/harvard.cs50.droplet/blob/master/droplet.js#L255!

Screencast: 
[no-extension.zip](https://github.com/cs50/harvard.cs50.droplet/files/434546/no-extension.zip)

**Comment by kzidane** [comment]
This error also seems to cause tab buttons to become in a messy state (e.g., transparent backgrounds, wrong background colors, etc)

![tab-background-transparent](https://cloud.githubusercontent.com/assets/7230211/17929183/12cece72-69ff-11e6-9bd3-04275abd96f5.png)
![tab-background-mismatch-0](https://cloud.githubusercontent.com/assets/7230211/17929181/12ca3c5e-69ff-11e6-92b3-6742523cdbc1.png)
![tab-background-mismatch-1](https://cloud.githubusercontent.com/assets/7230211/17929182/12cae85c-69ff-11e6-9bbd-8c1f5be2a1dd.png)

**Comment by dabbler0** [comment]
Ah I see. This should be a quick fix, I'll do it tonight.

**Comment by dabbler0** [comment]
This should be fixed by commit to master 5a2179bfd4e7270122b26eb7f42eaf36dd682cfd.
