### ISSUE TITLE
perhaps console.log only in debug mode?

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#70]
(e.g., https://github.com/cs50/harvard.cs50.droplet/blob/master/droplet.js#L610). Might https://github.com/cs50/core/blob/master/plugins/c9.core/c9.js#L211 be of help?

**Comment by crossroads1112** [comment]
This has already been fixed I believe
https://github.com/cs50/harvard.cs50.droplet/blob/de742e10786361a71e69d64ad2a80bb0878a2519/droplet.js#L136

**Comment by kzidane** [comment]
Not quite sure 136 in de742e1 is relevant. The `debug` plugin deals with code debuggers. By debug mode I mean Cloud9's debug mode. You should be able to access the `debug` property on the `c9` plugin per https://github.com/cs50/harvard.cs50.droplet/issues/70#issue-252347070?

**Comment by crossroads1112** [comment]
Oh, well in any case, droplet no longer prints to the console so I think this issue is still resolved.
