### ISSUE TITLE
update get_* functions to take one or more args?

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#75]
e.g., https://github.com/cs50/libcs50/blob/develop/src/cs50.h#L155

**Comment by dabbler0** [comment]
I've updated it to allow more arguments, but I don't know what the single required argument is? reference.cs50.net still claims it takes no argument: https://reference.cs50.net/cs50/get_char

**Comment by kzidane** [comment]
Afraid reference50 is dated! We'll update it asap. These should take the
same arguments as printf now.

**Comment by crossroads1112** [comment]
`get_*` technically so support being called with no args but this is for legacy (cs50x) reasons. The man pages don't reflect this, so droplet probably shouldn't either.

**Comment by kzidane** [comment]
That's what I thought too, given that we're probably gonna remove support
for 0 args soon?

**Comment by crossroads1112** [comment]
Ideally yes, but the when is a bit unclear atm. CS50x is only ever a year behind but iirc, it's possible that courses which require translations could lag further behind than that, at least that is what I remember from the last time this was discussed.

**Comment by crossroads1112** [comment]
And even then, the functionality may stay in the library but cause a compile-tine deprecation warning (similar to `Get*`).

**Comment by dabbler0** [comment]
Changed to have one argument, which I've called `format` in the palette.
