### ISSUE TITLE
Pre- and Post- Increment and Decrement, and GT and LT Blocks

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#9]
Good idea to add blocks for pre- and post- increment and decrement operations, and >= and <=?

**Comment by dmalan** [comment]
Anthony, how did you envision these working? Any reason not to add to
operators?

**Comment by dabbler0** [comment]
No reason not to! We can add them to the "Operations" section?

General note for when I'm not around -- playing around with adding or removing things from the palette is built to be relatively easy: add or remove an element from "c_cpp.json," which contains a structure like this:
```
{
  // ... some other properties
  'palette': [
    // ...some other categories
    {
      'name': 'Category Name', // The category we want to put the block under
      'blocks': [
        { // This object represents one block:
          'block': 'someCode()', // Text code for the block
          'context': 'expression', // Usually 'blockItem' (statement) or 'expression' (value)
          'title': '<b>html</b> formatted tooltip text',
        }
        // .. and more blocks in this category
      ]
    }
    // ...and more palette categories
  ]
}
```

**Comment by dabbler0** [comment]
Added to master.
