### ISSUE TITLE
Uncaught ReferenceError when resizing the palette

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#91]
![resize-palette](https://user-images.githubusercontent.com/7230211/38100096-673fa736-334a-11e8-807d-e742c4166c9e.gif)

**Comment by dlloyd09** [comment]
@crossroads1112 this issue and #92 I think we should try and squash quickly if we can! I'm less concerned about #87. Most important is getting this out. So long as JS errors aren't breaking the IDE overall, we're okay with things needing a bit more fine-tuning. (cc @malan)

**Comment by crossroads1112** [comment]
Oh wait, I meant for that commit to resolve the other one

**Comment by crossroads1112** [comment]
@kzidane I can't seem to replicate this. Is there anything in particular you did to trigger this?

**Comment by kzidane** [comment]
Nope, just dragged the vertical bar per the GIF. Are you using Chrome?

**Comment by crossroads1112** [comment]
I am yes, latest version and all

**Comment by kzidane** [comment]
What version of Chrome are you using? Mine is 65.0.3325.181.

**Comment by kzidane** [comment]
I'm also testing an a hosted workspace (not locally). If still can't replicate, I can show you how to test online.

**Comment by crossroads1112** [comment]
I'm using 65.0.3325.181 as well.

I am still unable to replicate, so I would appreciate that.
